name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia 'main' si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      # Opcional: Si necesitas construir tu sitio (ej. con React o Vue)
      # - name: Install Dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
